author: Ron Lancaster
copyright: 2024
description: >-
  Thoughts on tech and leadership
title: Ron Lancaster
url: "https://www.ronlancaster.com"

# Output options
excerpt_separator: <!--more-->
markdown: kramdown
permalink: /posts/:title
timezone: US/Central

# Define additional collections
collections:
  notes:
    output: true
    permalink: /notes/:title

# Add these pages to the default list of inclusions.
include:
  - _pages

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - _site/
  - .idea/
  - .github/
