author: Ron Lancaster
copyright: 2024
description: >-
  Thoughts on tech and leadership
email: doc@firelord.net
title: Ron Lancaster
url: "https://www.ronlancaster.com"

# Output options
markdown: kramdown
permalink: /writing/:title:output_ext
timezone: US/Central

include:
  - _pages

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - _site/
  - .idea/
  - .github/