author: Ron Lancaster
copyright: 2024
description: >- # this means to ignore newlines until "baseurl:" 
  Thoughts on tech and leadership
email: me@ronlancaster.com
title: Ron Lancaster
url: "https://www.ronlancaster.com" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
timezone: US/Central